#include "TROOT.h"
#include "TFile.h"
#include "TTree.h"
#include "TBrowser.h"
#include "TH2.h"
#include "TRandom.h"
void tree1w()
{
   //create a Tree file tree1.root
   //create the file, the Tree and a few branches
   TFile f("tree1.root","recreate");
   TTree t1("t1","a simple Tree with simple variables");
   Float_t signal;
   t1.Branch("signal",&signal,"signal/F");
   //fill the tree
   for (Int_t i=0;i<10000;i++) {
     signal = gRandom->Gaus();
     t1.Fill();
}
t1.Write();
}
   
void tree1r()
{
   //read the Tree generated by tree1w and fill two histograms
   //note that we use "new" to create the TFile and TTree objects !
   //because we want to keep these objects alive when we leave this function.
   TFile *f = new TFile("tree1.root");
   TTree *t1 = (TTree*)f->Get("t1");
   Float_t signal;
   t1->SetBranchAddress("signal",&signal);
   
   //create two histograms
   TH1F *h_x   = new TH1F("h_x","signal distribution",100,-5,5);
   h_x->SetXTitle("x");
   h_x->SetYTitle("signal");
   //read all entries and fill the histograms
   Long64_t nentries =t1 ->GetEntries();
   for(Long64_t i=0;i<nentries;i++) {
     t1->GetEntry(i);
     h_x->Fill(signal);
     h_x->SetLineColor(2);
  }
  //we do not close the file. We want to keep the generated histograms
  //we open a browser and the TreeViewer
  //if (gROOT->IsBatch()) return;
  //new TBrowser();
  //t1->StartViewer();
  TCanvas* c1 = new TCanvas("c1");
  h_x->Fit("gaus");
  c1->Print("rnfit.pdf");
  //we open a browser and the TreeViewer
 
  // in the browser, click on "ROOT Files", then on "tree1.root".
  //     you can click on the histogram icons in the right panel to draw them.
  // in the TreeViewer, follow the instructions in the Help button.
}
void tree2() {
   tree1w();
   tree1r();
}
